name = "YaoHelper"
uuid = "6c2c645b-7829-4a6b-84c8-29091e35444f"
authors = ["Yusheng Zhao <yushengzhao2020@outlook.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
